#pragma once

#include "runtime_version.h"

#define MMOD_ENGINE_VERSION_MAJOR 1
#define MMOD_ENGINE_VERSION_MINOR 2
#define MMOD_ENGINE_VERSION_PATCH 0

#define MMOD_ENGINE_VERSION_STRING MMOD_RUNTIME_VERSION_STRINGIFY3( \
    MMOD_ENGINE_VERSION_MAJOR, MMOD_ENGINE_VERSION_MINOR, MMOD_ENGINE_VERSION_PATCH)
#define MMOD_ENGINE_COMPONENT "engine"
