#pragma once

#include "runtime_version.h"

#define MMOD_CONSOLE_VERSION_MAJOR 1
#define MMOD_CONSOLE_VERSION_MINOR 2
#define MMOD_CONSOLE_VERSION_PATCH 0

#define MMOD_CONSOLE_VERSION_STRING MMOD_RUNTIME_VERSION_STRINGIFY3( \
    MMOD_CONSOLE_VERSION_MAJOR, MMOD_CONSOLE_VERSION_MINOR, MMOD_CONSOLE_VERSION_PATCH)
#define MMOD_CONSOLE_COMPONENT "mm-console"
