// AUTO-GENERATED by tools/sdk-verify/generate-static-asserts.ps1
// Generated: 2026-07-03 22:43:59 +03:00
// DO NOT EDIT - regeneration will overwrite manual changes.
//
// Compile-time SDK layout verification.
// When a generated header regen changes class sizes or member offsets,
// static_assert fires at compile time, preventing builds with wrong offsets.

#pragma once

#include "me_sdk/sdk_verify.h"

// ============================================================
// Class size verification
// ============================================================

MMOD_SDK_VERIFY_CLASS_SIZE(AActor, 0x01C0);
MMOD_SDK_VERIFY_CLASS_SIZE(AController, 0x02CC);
MMOD_SDK_VERIFY_CLASS_SIZE(AHUD, 0x0444);
MMOD_SDK_VERIFY_CLASS_SIZE(APawn, 0x03C4);
MMOD_SDK_VERIFY_CLASS_SIZE(APlayerController, 0x0528);
MMOD_SDK_VERIFY_CLASS_SIZE(ASkeletalMeshActorSpawnable, 0x01F4);
MMOD_SDK_VERIFY_CLASS_SIZE(ATdPawn, 0x08F8);
MMOD_SDK_VERIFY_CLASS_SIZE(ATdPlayerController, 0x0698);
MMOD_SDK_VERIFY_CLASS_SIZE(ATdPlayerPawn, 0x09E4);
MMOD_SDK_VERIFY_CLASS_SIZE(AWorldInfo, 0x0E0C);
MMOD_SDK_VERIFY_CLASS_SIZE(UArrayProperty, 0x0088);
MMOD_SDK_VERIFY_CLASS_SIZE(UBoolProperty, 0x0088);
MMOD_SDK_VERIFY_CLASS_SIZE(UByteProperty, 0x0088);
MMOD_SDK_VERIFY_CLASS_SIZE(UCanvas, 0x0088);
MMOD_SDK_VERIFY_CLASS_SIZE(UClass, 0x01F4);
MMOD_SDK_VERIFY_CLASS_SIZE(UClassProperty, 0x008C);
MMOD_SDK_VERIFY_CLASS_SIZE(UComponent, 0x0048);
MMOD_SDK_VERIFY_CLASS_SIZE(UConsole, 0x0194);
MMOD_SDK_VERIFY_CLASS_SIZE(UDelegateProperty, 0x008C);
MMOD_SDK_VERIFY_CLASS_SIZE(UEngine, 0x03AC);
MMOD_SDK_VERIFY_CLASS_SIZE(UEnum, 0x0050);
MMOD_SDK_VERIFY_CLASS_SIZE(UField, 0x0044);
MMOD_SDK_VERIFY_CLASS_SIZE(UFloatProperty, 0x0084);
MMOD_SDK_VERIFY_CLASS_SIZE(UFunction, 0x00B0);
MMOD_SDK_VERIFY_CLASS_SIZE(UGameEngine, 0x04AC);
MMOD_SDK_VERIFY_CLASS_SIZE(UGameViewportClient, 0x0100);
MMOD_SDK_VERIFY_CLASS_SIZE(UInterface, 0x003C);
MMOD_SDK_VERIFY_CLASS_SIZE(UIntProperty, 0x0084);
MMOD_SDK_VERIFY_CLASS_SIZE(UMaterial, 0x02BC);
MMOD_SDK_VERIFY_CLASS_SIZE(UMaterialInterface, 0x005C);
MMOD_SDK_VERIFY_CLASS_SIZE(UObject, 0x003C);
MMOD_SDK_VERIFY_CLASS_SIZE(UObjectProperty, 0x0088);
MMOD_SDK_VERIFY_CLASS_SIZE(UProperty, 0x0084);
MMOD_SDK_VERIFY_CLASS_SIZE(USkeletalMesh, 0x026C);
MMOD_SDK_VERIFY_CLASS_SIZE(USkeletalMeshComponent, 0x0450);
MMOD_SDK_VERIFY_CLASS_SIZE(UState, 0x00E4);
MMOD_SDK_VERIFY_CLASS_SIZE(UStruct, 0x0090);
MMOD_SDK_VERIFY_CLASS_SIZE(UTdConsole, 0x01C0);
MMOD_SDK_VERIFY_CLASS_SIZE(UTdGameEngine, 0x0520);
MMOD_SDK_VERIFY_CLASS_SIZE(UTdGameViewportClient, 0x0114);

// ── New types added 2026-07-14 (safe_state / safe_gameplay) ─────────

MMOD_SDK_VERIFY_CLASS_SIZE(ACheckpoint, 0x0318);
MMOD_SDK_VERIFY_CLASS_SIZE(AGameReplicationInfo, 0x0254);
MMOD_SDK_VERIFY_CLASS_SIZE(ANavigationPoint, 0x0314);
MMOD_SDK_VERIFY_CLASS_SIZE(APlayerReplicationInfo, 0x0258);
MMOD_SDK_VERIFY_CLASS_SIZE(ATdCheckpoint, 0x0338);
MMOD_SDK_VERIFY_CLASS_SIZE(ATdGameReplicationInfo, 0x0268);
MMOD_SDK_VERIFY_CLASS_SIZE(ATdPlayerReplicationInfo, 0x0264);
MMOD_SDK_VERIFY_CLASS_SIZE(ATdStashpoint, 0x01E4);
MMOD_SDK_VERIFY_CLASS_SIZE(ATdTeamInfo, 0x0214);
MMOD_SDK_VERIFY_CLASS_SIZE(ATeamInfo, 0x01DC);
MMOD_SDK_VERIFY_CLASS_SIZE(UMapInfo, 0x003C);
MMOD_SDK_VERIFY_CLASS_SIZE(UTdMapInfo, 0x005C);

// ============================================================
// Key member offset verification
// These members are accessed directly by engine hooks at runtime.
// ============================================================

MMOD_SDK_VERIFY_MEMBER_OFFSET(UObject, Name,    0x002C);
MMOD_SDK_VERIFY_MEMBER_OFFSET(UObject, Outer,   0x0028);
MMOD_SDK_VERIFY_MEMBER_OFFSET(UObject, Class,   0x0034);
