#Requires -Version 5.1
<#
.SYNOPSIS
  Generate static_assert code from documented class sizes.
  Output: shared/me_sdk/sdk_verify_generated.h (auto-generated, DO NOT EDIT).
#>
param(
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"
$ToolDir = $PSScriptRoot
# $ToolDir = .../tools/sdk-verify → go up 2 levels to repo root
$Root = Split-Path (Split-Path $ToolDir -Parent) -Parent
$SdkDir = Join-Path $Root "shared\me_sdk"

if (-not $OutputPath) {
    $OutputPath = Join-Path $SdkDir "sdk_verify_generated.h"
}

$knownClasses = [System.Collections.ArrayList]::new()
[void]$knownClasses.Add(@{cpp='UObject';                     size=0x003C})
[void]$knownClasses.Add(@{cpp='UField';                      size=0x0044})
[void]$knownClasses.Add(@{cpp='UEnum';                       size=0x0050})
[void]$knownClasses.Add(@{cpp='UProperty';                   size=0x0084})
[void]$knownClasses.Add(@{cpp='UByteProperty';               size=0x0088})
[void]$knownClasses.Add(@{cpp='UIntProperty';                size=0x0084})
[void]$knownClasses.Add(@{cpp='UFloatProperty';              size=0x0084})
[void]$knownClasses.Add(@{cpp='UBoolProperty';               size=0x0088})
[void]$knownClasses.Add(@{cpp='UObjectProperty';             size=0x0088})
[void]$knownClasses.Add(@{cpp='UClassProperty';              size=0x008C})
[void]$knownClasses.Add(@{cpp='UArrayProperty';              size=0x0088})
[void]$knownClasses.Add(@{cpp='UDelegateProperty';           size=0x008C})
[void]$knownClasses.Add(@{cpp='UStruct';                     size=0x0090})
[void]$knownClasses.Add(@{cpp='UFunction';                   size=0x00B0})
[void]$knownClasses.Add(@{cpp='UState';                      size=0x00E4})
[void]$knownClasses.Add(@{cpp='UClass';                      size=0x01F4})
[void]$knownClasses.Add(@{cpp='UComponent';                  size=0x0048})
[void]$knownClasses.Add(@{cpp='UInterface';                  size=0x003C})
[void]$knownClasses.Add(@{cpp='AActor';                      size=0x01C0})
[void]$knownClasses.Add(@{cpp='APawn';                       size=0x03C4})
[void]$knownClasses.Add(@{cpp='AController';                 size=0x02CC})
[void]$knownClasses.Add(@{cpp='APlayerController';           size=0x0528})
[void]$knownClasses.Add(@{cpp='UCanvas';                     size=0x0088})
[void]$knownClasses.Add(@{cpp='UGameViewportClient';         size=0x0100})
[void]$knownClasses.Add(@{cpp='UEngine';                     size=0x03AC})
[void]$knownClasses.Add(@{cpp='UGameEngine';                 size=0x04AC})
[void]$knownClasses.Add(@{cpp='AWorldInfo';                  size=0x0E0C})
[void]$knownClasses.Add(@{cpp='AHUD';                        size=0x0444})
[void]$knownClasses.Add(@{cpp='UConsole';                    size=0x0194})
[void]$knownClasses.Add(@{cpp='ASkeletalMeshActorSpawnable'; size=0x01F4})
[void]$knownClasses.Add(@{cpp='USkeletalMeshComponent';      size=0x0450})
[void]$knownClasses.Add(@{cpp='USkeletalMesh';               size=0x026C})
[void]$knownClasses.Add(@{cpp='UMaterialInterface';          size=0x005C})
[void]$knownClasses.Add(@{cpp='UMaterial';                   size=0x02BC})
[void]$knownClasses.Add(@{cpp='UTdGameEngine';               size=0x0520})
[void]$knownClasses.Add(@{cpp='UTdGameViewportClient';       size=0x0114})
[void]$knownClasses.Add(@{cpp='UTdConsole';                  size=0x01C0})
[void]$knownClasses.Add(@{cpp='ATdPlayerController';         size=0x0698})
[void]$knownClasses.Add(@{cpp='ATdPawn';                     size=0x08F8})
[void]$knownClasses.Add(@{cpp='ATdPlayerPawn';               size=0x09E4})

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss K"

# Build header content
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// AUTO-GENERATED by tools/sdk-verify/generate-static-asserts.ps1')
[void]$sb.AppendLine("// Generated: $timestamp")
[void]$sb.AppendLine('// DO NOT EDIT - regeneration will overwrite manual changes.')
[void]$sb.AppendLine('//')
[void]$sb.AppendLine('// Compile-time SDK layout verification.')
[void]$sb.AppendLine('// When a generated header regen changes class sizes or member offsets,')
[void]$sb.AppendLine('// static_assert fires at compile time, preventing builds with wrong offsets.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include "me_sdk/sdk_verify.h"')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// ============================================================')
[void]$sb.AppendLine('// Class size verification')
[void]$sb.AppendLine('// ============================================================')
[void]$sb.AppendLine('')

$sorted = $knownClasses | Sort-Object { $_.cpp }
foreach ($cls in $sorted) {
    $sizeHex = "0x{0:X4}" -f $cls.size
    [void]$sb.AppendLine("MMOD_SDK_VERIFY_CLASS_SIZE($($cls.cpp), $sizeHex);")
}
[void]$sb.AppendLine('')

[void]$sb.AppendLine('// ============================================================')
[void]$sb.AppendLine('// Key member offset verification')
[void]$sb.AppendLine('// These members are accessed directly by engine hooks at runtime.')
[void]$sb.AppendLine('// ============================================================')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('MMOD_SDK_VERIFY_MEMBER_OFFSET(UObject, Name,    0x002C);')
[void]$sb.AppendLine('MMOD_SDK_VERIFY_MEMBER_OFFSET(UObject, Outer,   0x0028);')
[void]$sb.AppendLine('MMOD_SDK_VERIFY_MEMBER_OFFSET(UObject, Class,   0x0034);')

$utf8 = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutputPath, $sb.ToString(), $utf8)

Write-Host "Generated: $OutputPath" -ForegroundColor Green
Write-Host "  Classes: $($knownClasses.Count)" -ForegroundColor Green
Write-Host "  Members: 3" -ForegroundColor Green
