#pragma once

#include "runtime_version.h"

#define MMOD_MANAGER_VERSION_MAJOR 1
#define MMOD_MANAGER_VERSION_MINOR 2
#define MMOD_MANAGER_VERSION_PATCH 0

#define MMOD_MANAGER_VERSION_STRING MMOD_RUNTIME_VERSION_STRINGIFY3( \
    MMOD_MANAGER_VERSION_MAJOR, MMOD_MANAGER_VERSION_MINOR, MMOD_MANAGER_VERSION_PATCH)
#define MMOD_MANAGER_COMPONENT "module_manager"
